### ISSUE TITLE
Playlist keeps playing one song in both Mac and Android 

### ISSUE THREAD

**Issue by zoeyjin** [hepuxuan/haiwaimusic#1]
I added a few songs to my playlist but it keeps playing the first song, without going to the next one automatically. I have to manually trigger the next song. 
Also, could we have a "play" button for the playlist, as currently I need to manually click on a song to start playing it.
Mac: macOS Sierra, 10.12.6, MacBook Pro
Android: 6.0.1, Nexus 5X.
Happy to provide more info if needed and thank you for developing it!

**Comment by hepuxuan** [comment]
Thanks for submitting the issue, will look into this issue

**Comment by hepuxuan** [comment]
The issue should have been fixed
